/**
 * Gramática en-US.
 *
 * Mesma ideia da pt-BR: o vocabulário de verbos é um conjunto fechado e pequeno, e cada
 * variação que falta vira um comando perdido. Vale ser generoso — o custo de uma entrada
 * a mais aqui é zero.
 *
 * Duas diferenças em relação ao português que mudam o formato das listas:
 * - O inglês quase não conjuga, então em vez de seis formas de "correu" o que existe é
 *   uma nuvem de gírias ("bailed", "dropped out", "tapped out"). O peso sai das listas
 *   simples e vai para `phraseRewrites`, onde ficam os verbos de duas palavras.
 * - A ordem Sujeito-Verbo é bem mais rígida ("Chris won"), mas o parser aceita as duas
 *   ordens de qualquer jeito, então nada precisa mudar por causa disso.
 *
 * Não é preciso normalizar à mão: `compileGrammar` aplica `normalizeToken` em tudo.
 */

import type { Grammar } from './types';

export const enUS: Grammar = {
  locale: 'en-US',

  actions: {
    // Ganhou a rodada. Em Cacheta só pode haver um por rodada.
    won: [
      'won',
      'win',
      'wins',
      'winner',
      'beat',
      'beats',
      'knocked',
      'knocks',
      'closed',
      'closes',
      'took',
      'takes',
      'swept',
      'sweeps',
    ],
    // Desistiu da rodada, -1 ponto. Em inglês o verbo natural é "fold", de pôquer.
    fold: [
      'folded',
      'folds',
      'fold',
      'dropped',
      'drops',
      'drop',
      'ran',
      'runs',
      'quit',
      'quits',
      'passed',
      'passes',
      'pass',
      'bailed',
      'bails',
      'bail',
      'skipped',
      'skips',
      'ducked',
      'ducks',
      'bounced',
      'escaped',
      'escapes',
    ],
    // Perdeu jogando até o fim, -2 pontos.
    lost: [
      'lost',
      'lose',
      'loses',
      'losing',
      'paid',
      'pays',
      'pay',
      'busted',
      'busts',
      'bust',
      'died',
      'dies',
      'crashed',
      'tanked',
      'sank',
      'blew',
      'flopped',
    ],
  },

  // Fodinha: o verbo é só o portador, quem decide bid vs vazas é a fase da rodada.
  valueVerbs: [
    'bet',
    'bets',
    'bid',
    'bids',
    'called',
    'calls',
    'call',
    'said',
    'says',
    'say',
    'made',
    'makes',
    'make',
    'got',
    'gets',
    'get',
    'took',
    'takes',
    'take',
    'won',
    'wins',
    'win',
    'guessed',
    'guesses',
    'guess',
    'asked',
    'asks',
    'ask',
    'claimed',
    'claims',
    'claim',
    'needs',
    'need',
  ],

  advance: [
    'next round',
    'next hand',
    'next',
    'end round',
    'end the round',
    'finish round',
    'finish the round',
    'close the round',
    'confirm bets',
    'confirm the bets',
    'confirm',
    'lock it in',
    'lock in',
    'apply',
    'apply it',
    'were done',
  ],

  undo: [
    'undo',
    'undo that',
    'scratch that',
    'forget that',
    'nevermind',
    'never mind',
    'delete',
    'remove',
    'cancel',
    'go back',
  ],

  numbers: {
    zero: 0,
    none: 0,
    nothing: 0,
    nil: 0,
    zip: 0,
    one: 1,
    two: 2,
    three: 3,
    four: 4,
    five: 5,
    six: 6,
    seven: 7,
    eight: 8,
    nine: 9,
    ten: 10,
    eleven: 11,
    twelve: 12,
    thirteen: 13,
    fourteen: 14,
    fifteen: 15,
  },

  connectives: ['and', 'with', 'plus'],

  fillers: [
    'the',
    'a',
    'an',
    'he',
    'she',
    'they',
    'them',
    'it',
    'his',
    'her',
    'their',
    'there',
    'then',
    'here',
    'like',
    'that',
    'this',
    'of',
    'for',
    'to',
    'too',
    'so',
    'also',
    'now',
    'just',
    'ok',
    'okay',
    'well',
    'uh',
    'um',
    'yeah',
    'right',
    'tricks',
    'trick',
    'points',
    'point',
    // Palavras de apoio das expressões compostas: sem isto elas sobram procurando dono.
    'round',
    'hand',
    'game',
    'match',
    'out',
    'in',
    'up',
    'down',
    'away',
    'everything',
    // Auxiliares que aparecem entre o nome e o verbo: "Chris IS GONNA make two".
    'is',
    'are',
    'was',
    'were',
    'has',
    'have',
    'had',
    'did',
    'does',
    'do',
    'will',
    'would',
    'gonna',
    'going',
    'wants',
    'want',
    'can',
    'could',
    'should',
    'im',
    'ill',
    'hes',
    'shes',
    'theyre',
  ],

  positional: ['player', 'number', 'seat', 'chair'],

  quantifiers: {
    // "all" é curto o bastante para colidir com um jogador chamado Al — mas "all folded"
    // é natural demais para ficar de fora. A fila pendente é a rede: nada é aplicado sem
    // o usuário conferir.
    all: ['everyone', 'everybody', 'all'],
    rest: ['rest', 'others', 'remaining', 'remainder'],
  },

  phraseRewrites: [
    // Quantificadores compostos.
    ['everyone else', 'rest'],
    ['everybody else', 'rest'],
    ['all the others', 'rest'],
    ['the others', 'rest'],
    ['the rest', 'rest'],
    ['the remaining', 'rest'],
    ['all of them', 'everyone'],
    ['the whole table', 'everyone'],
    ['the table', 'everyone'],
    // Verbos compostos de "fold".
    ['dropped out', 'folded'],
    ['drops out', 'folded'],
    ['drop out', 'folded'],
    ['ran away', 'folded'],
    ['ran out', 'folded'],
    ['bailed out', 'folded'],
    ['tapped out', 'folded'],
    ['sat out', 'folded'],
    ['sits out', 'folded'],
    ['backed out', 'folded'],
    ['walked away', 'folded'],
    ['stepped out', 'folded'],
    ['pulled out', 'folded'],
    ['gave up', 'folded'],
    ['gives up', 'folded'],
    ['chickened out', 'folded'],
    ['bowed out', 'folded'],
    ['didnt play', 'folded'],
    ['did not play', 'folded'],
    // Verbos compostos de "won". "went out" é o termo de rummy para bater.
    ['won the round', 'won'],
    ['won the hand', 'won'],
    ['won it', 'won'],
    ['took the round', 'won'],
    ['took the hand', 'won'],
    ['took it', 'won'],
    ['went out', 'won'],
    ['goes out', 'won'],
    ['closed it out', 'won'],
    ['cleaned up', 'won'],
    // Verbos compostos de "lost".
    ['lost the round', 'lost'],
    ['lost the hand', 'lost'],
    ['went down', 'lost'],
    ['blew it', 'lost'],
    ['ate it', 'lost'],
    ['paid up', 'lost'],
    ['paid for it', 'lost'],
    ['got smoked', 'lost'],
    ['took the loss', 'lost'],
    // Negação + verbo de valor. Três tokens primeiro: `compileGrammar` ordena as
    // reescritas da mais longa para a mais curta, então "didnt make any" ganha de
    // "didnt make". As de três colapsam direto para o zero — o número solto fecha a
    // oração sozinho, exatamente como "Chris zero".
    ['didnt make any', 'none'],
    ['didnt get any', 'none'],
    ['didnt win any', 'none'],
    ['didnt take any', 'none'],
    ['did not make any', 'none'],
    ['made none', 'none'],
    ['got none', 'none'],
    ['no tricks', 'none'],
    // ...e as de dois deixam o verbo, para o "nothing"/"zero" que vem depois virar o valor.
    ['didnt make', 'make'],
    ['didnt get', 'get'],
    ['didnt win', 'win'],
    ['didnt take', 'take'],
    ['didnt bid', 'bid'],
    ['didnt bet', 'bet'],
    ['didnt call', 'call'],
    ['isnt making', 'make'],
    ['not making', 'make'],
  ],
};
