/**
 * Gramática pt-BR.
 *
 * O vocabulário de verbos é um conjunto fechado e pequeno — é a metade fácil do
 * problema. Vale ser generoso com sinônimos e conjugações, porque cada variação que
 * falta vira um comando perdido, e o custo de uma entrada a mais aqui é zero.
 *
 * Não é preciso normalizar à mão: `compileGrammar` aplica `normalizeToken` em tudo.
 */

import type { Grammar } from './types';

export const ptBR: Grammar = {
  locale: 'pt-BR',

  actions: {
    // Ganhou a rodada. Em Cacheta só pode haver um por rodada.
    won: [
      'ganhou',
      'ganharam',
      'ganha',
      'ganho',
      'ganhei',
      'bateu',
      'bateram',
      'bate',
      'bati',
      'venceu',
      'venceram',
      'vence',
      'fechou',
      'fecharam',
      'fecha',
      'matou',
      'mataram',
      'gabou',
    ],
    // "Correu" = desistiu da rodada, -1 ponto.
    fold: [
      'correu',
      'correram',
      'corre',
      'correndo',
      'corri',
      'fugiu',
      'fugiram',
      'foge',
      'caiu',
      'caíram',
      'desistiu',
      'desistiram',
      'desiste',
      'pulou',
      'pularam',
      'pula',
      'passou',
      'passaram',
      'passa',
      'saiu',
      'saíram',
      'vazou',
      'vazaram',
      'abandonou',
      'abandonaram',
      'escapou',
      'escaparam',
    ],
    // Perdeu jogando até o fim, -2 pontos.
    lost: [
      'perdeu',
      'perderam',
      'perde',
      'perdi',
      'pagou',
      'pagaram',
      'paga',
      'paguei',
      'levou',
      'levaram',
      'leva',
      'tomou',
      'tomaram',
      'estourou',
      'estouraram',
      'morreu',
      'morreram',
      'dançou',
      'dançaram',
      'rodou',
      'rodaram',
      'sentou',
      'sentaram',
    ],
  },

  // Fodinha: o verbo é só o portador, quem decide bid vs vazas é a fase da rodada.
  valueVerbs: [
    'apostou',
    'apostaram',
    'aposta',
    'apostei',
    'pediu',
    'pediram',
    'pede',
    'chamou',
    'chamaram',
    'falou',
    'falaram',
    'fez',
    'fizeram',
    'faz',
    'ganhou',
    'ganharam',
    'venceu',
    'venceram',
    'tirou',
    'tiraram',
    // Infinitivos: "vai FAZER duas", "quer APOSTAR três". Sem eles a forma mais natural
    // de anunciar uma aposta não era reconhecida.
    'fazer',
    'apostar',
    'ganhar',
    'pedir',
    'chamar',
    'falar',
    'tirar',
    'vencer',
  ],

  advance: [
    'proxima rodada',
    'proxima',
    'finalizar rodada',
    'finaliza rodada',
    'fechar rodada',
    'fecha rodada',
    'encerrar rodada',
    'confirmar apostas',
    'confirma apostas',
    'aplicar',
    'aplica',
    'pode aplicar',
  ],

  undo: ['desfazer', 'desfaz', 'apagar', 'apaga', 'cancelar', 'cancela', 'voltar', 'volta'],

  numbers: {
    zero: 0,
    nada: 0,
    nenhuma: 0,
    nenhum: 0,
    um: 1,
    uma: 1,
    dois: 2,
    duas: 2,
    tres: 3,
    quatro: 4,
    cinco: 5,
    seis: 6,
    // "meia" = 6 no português falado do Brasil.
    meia: 6,
    sete: 7,
    oito: 8,
    nove: 9,
    dez: 10,
    onze: 11,
    doze: 12,
    treze: 13,
    catorze: 14,
    quatorze: 14,
    quinze: 15,
  },

  connectives: ['e', 'com', 'mais'],

  fillers: [
    'o',
    'a',
    'os',
    'as',
    'ele',
    'ela',
    'eles',
    'elas',
    'seu',
    'sua',
    'ai',
    'ali',
    'la',
    'entao',
    'ne',
    'tipo',
    'que',
    'de',
    'do',
    'da',
    'pro',
    'pra',
    'ja',
    'so',
    'tambem',
    'agora',
    'vai',
    'ta',
    'vazas',
    'vaza',
    'pontos',
    'ponto',
    // Palavras de apoio das expressões compostas: sem isto elas sobram procurando dono.
    'rodada',
    'mao',
    'jogo',
    'partida',
    'fora',
    'tudo',
    // Auxiliares que aparecem entre o nome e o verbo: "matheus VAI fazer duas".
    'quer',
    'querem',
    'vou',
    'vamos',
    'pode',
    'podem',
    'em',
    'no',
    'na',
  ],

  positional: ['jogador', 'jogadora', 'player', 'numero', 'cadeira'],

  quantifiers: {
    all: ['todos', 'todas', 'geral'],
    rest: ['resto', 'outros', 'demais', 'restante', 'restantes'],
  },

  phraseRewrites: [
    // Quantificadores compostos.
    ['todo mundo', 'todos'],
    ['todos eles', 'todos'],
    ['o resto', 'resto'],
    ['os outros', 'resto'],
    ['os demais', 'resto'],
    ['o restante', 'resto'],
    // Verbos compostos de "correu".
    ['pulou fora', 'correu'],
    ['pularam fora', 'correram'],
    ['caiu fora', 'correu'],
    ['saiu fora', 'correu'],
    ['correu fora', 'correu'],
    ['deu no pe', 'correu'],
    ['foi embora', 'correu'],
    ['nao jogou', 'correu'],
    // Verbos compostos de "ganhou".
    ['bateu a mao', 'ganhou'],
    ['ganhou a rodada', 'ganhou'],
    ['levou a rodada', 'ganhou'],
    ['fechou o jogo', 'ganhou'],
    ['ganhou a mao', 'ganhou'],
    // Negação + verbo de valor: "não vai fazer nada" é o mesmo que "fez zero". Colapsa
    // para o verbo sozinho, e o "nada" que vem depois entra como o número.
    ['nao vai fazer', 'fazer'],
    ['nao vai pedir', 'pedir'],
    ['nao vai apostar', 'apostar'],
    ['nao fez', 'fez'],
    ['nao pediu', 'pediu'],
    ['nao apostou', 'apostou'],
    // Verbos compostos de "perdeu".
    ['perdeu a rodada', 'perdeu'],
    ['pagou tudo', 'perdeu'],
    ['se ferrou', 'perdeu'],
    ['foi de base', 'perdeu'],
  ],
};
